PROJECT_NAME := sys-monitor-esp8266

EXTRA_COMPONENT_DIRS = $(IDF_PATH)/examples/common_components/protocol_examples_common
EXTRA_COMPONENT_DIRS += smon-component

include $(IDF_PATH)/make/project.mk
